### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by Ruff9** [jroblak/MelonJS-Node-Socket.IO-Boilerplate-Example#6]
After installing all the dependencies, I runned node server.js in the server folder. 

On my http://localhost:8080/ nothing shows, and I can see : "Cannot GET /".

Any idea?

**Comment by jroblak** [comment]
Did you change the network.host to localhost in game.js?

**Comment by jroblak** [comment]
Oh! You also have to alter something in index.html:

```
<script src="http://ec2-54-234-85-69.compute-1.amazonaws.com/socket.io/socket.io.js"></script>
```

to

```
<script src="http://localhost:8080/socket.io/socket.io.js"></script>
```
